### ISSUE TITLE
Consider using snponly.efi for UEFI boot (iPXE gets stuck)

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/sidero#1042]
Hey!

So I've been working on setting up a Kubernetes cluster with Sidero. I have two Dell R430s and two Dell R720s.

The two R430s boot perfectly fine, but none of the R720s boot correctly. They all get stuck on `iPXE initialising devices...`.

I've seen other users of Sidero mention this same behaviour here:
- https://github.com/siderolabs/sidero/issues/447
- https://github.com/siderolabs/sidero/issues/447#issuecomment-1143920453

The two R430s are using `Intel X520-DA2` NICs and the R720s are using `HPE NC552SFP` (`Emulex OCE11102`). I tried swapping an Intel NIC into one of the R720s but it didn't help.

I came across this iPXE issue and think it could be related.

https://github.com/ipxe/ipxe/issues/250

They seem to suggest that `snponly.EFI` could work better than `ipxe.efi`. Another project seems to have faced a similar issue and saw success with this recommendation.

https://github.com/warewulf/warewulf3/issues/84

Any help would be hugely appreciated, thank you.

**Comment by smira** [comment]
thank you, sounds like an easy solution to offer that as well

**Comment by uhthomas** [comment]
Awesome, I look forward to it.

I'm sort of blocked from deploying Sidero/Talos until this is available. Is there anything I can do to help?

**Comment by smira** [comment]
I don't have any exact timeline at the moment, we need to get the master version of Sidero forward with this and other changes
