### ISSUE TITLE
talos does not refresh config from sidero during upgrade

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/sidero#1088]
I understand that the configuration in the sidero cluster will not be applied automatically when applied to the cluster, though it was my understand the configuration would be applied during an upgrade of a workload machine? This does not seem to be the case.

**Comment by smira** [comment]
Sidero doesn't push the machine config to Talos, it's the opposite, Talos fetches the machine config from Sidero. As the machine config is persisted on Talos side, it never re-fetches the config unless you wipe the `STATE` partition (or the whole node). Note that wiping `STATE` partition might have other effects as well, e.g. the node will change its `machine-id`.

**Comment by smira** [comment]
> @smira So, what's the correct way to update the configuration? I want to be able to install system extensions without wiping the entire node as they have storage disks for rook ceph.

I guess it's not possible in general with CAPI, as CAPI rolls out updates by _replacing_ nodes.

But with Talos you can still use `talosctl patch config/apply-config` to push changes to the nodes outside of CAPI flow.

**Comment by uhthomas** [comment]
@smira I appreciate your feedback. Is it possible to raise an issue with CAPI? This seems ridiculous in practise. How does it make any sense to fully wipe a storage node just to change some config? This is not directed toward you, Talos or Sidero, but rather the design of CAPI. Is there really no other way? I was so excited at the prospect of managing nodes as configuration like I have attempted to do here: https://github.com/uhthomas/automata/blob/a7dad873950c462513ba5341c2c9e5bba0d3956b/k8s/unwind_bootstrap/server_list.cue

**Comment by smira** [comment]
I'm not much into CAPI these days, but my understanding is that it's more of a design thing - CAPI is more for cloud enironments with ephemeral VMs.

That's why we built [Omni](https://www.siderolabs.com/platform/saas-for-kubernetes/) to start with a different design which works better with Talos.
