### ISSUE TITLE
talosconfig

### ISSUE THREAD

**Issue by wsy0101** [siderolabs/sidero#1164]
I would like to raise a question. 

I have created two serverclasses, one for the master machine and the other for the worker machine. 

When two devices A and B start up, A serves as the main node of the cluster with an IP address of 172.16.1.108, and B serves as the working node of the cluster with an IP address of 172.16.1.107. Using configPatches, I will patch A and B separately. Patches A: "op": "replace", "path": "/machine/type", "Value": "contraplane", patch B: "op": "replace", "path": "/machine/type", "value": "worker".

 Why are the endpoints of the talosconfig generated in Secrets during the talos installation process 172.16.1.107 instead of 172.16.1.108? 

Through http://$PUBLIC_ IP: 8081/configdata? Uuid=$SERVER_ When UUID viewed the machine configuration file, it was also found that the configuration of 172.16.1.107 was complete, while the configuration of 172.16.1.108 was incomplete

**Comment by smira** [comment]
I'm lost a bit here, you shouldn't ever need to change the machine type via patches.

In any case the `endpoints` in the `talosconfig` automatically generated is based on addresses of the machines part of the controlplane (from the CAPI point of view).

**Comment by wsy0101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wsy0101** [comment]
This is because I had already decided to use the address 172.16.1.108 as the contraplane of Talos when the machine was not turned on, and 172.16.1.107 as the worker of Talos. 

However, during the installation process using side metal, the machine 172.16.1.107 was first taken over by side metal, resulting in the value of endpoints being 172.16.1.107 in the Talosconfig generated by Secrets, and I would prefer 172.16.1.108 with the role of contraplane as the endpoints.

The talos machine configuration file for this machine is complete, while the talos machine configuration file for the 172.16.1.108 machine that was later taken over by Sidero metal is incomplete

**Comment by smira** [comment]
You have a way to target specific machines for control plane and workers via server classes, but it's not supported to adjust machine type via config patches.
