### ISSUE TITLE
talos install by sidero-metal 

### ISSUE THREAD

**Issue by wsy0101** [siderolabs/sidero#1165]
I installed sidero metal in the k8s cluster. 

Cluster-0.yaml was generated through clusterctl.

After a machine starts, dhcp assigns an IP address to it, with the first IP address being 172.16.199. After the machine restarts, dhcp assigns an IP address of 172.16.1.200 to the machine again.

Through the watch kubectl get server, it was observed that the host name of the server was the IP of the second spray of dhcp: 172.16.1.200.

After executing kubectl apply - f cluster-0.yaml, accept the server and change the value of inspect to true.

After the machine was cleared to false and allocated to true, I believe that Sidero Metal should install the talos system for this machine. However, from the machine's display, I received the following error:

Features: DNS HTTP HTTPS iSCSITFTP AOE ELF MBOOT PXE bzImage Menu PXEXT
net0: 00:0c: 29:96:15:58 using unidirectionally on 0000:06:00.0 (Ethernet) [Closed]
[Link: up, TX: 0 TXE: 1 RX: 0 RXE: 0]
[TXE: 1 x "Network unreachable（ https://ipxe.org/28086011 ）]
Waiting for link up on net0... OK
Configuring (net0 @ 00:0c: 29:96:15:58)......OK
net0: 172.16.1.199/255.255.255.0 gw 172.16.1.1
http://172.16.1.101:8081/ipxe... No such file or directory（ https://ipxe.org/2d0c6136)

Failed to iPXE boot successfully via all interfaces
Retrying

I want to understand why dhcp allocates IP twice and why is net0 172.16.199

**Comment by smira** [comment]
DHCP questions I can't answer, as this is how your DHCP server works, it should probably prefer giving out same IP lease, but you can also configure it to use static leases per MAC address.

The iPXE error is not clear, you might need to look into full console logs

**Comment by MGlants** [comment]
same here,
dhco
chain url:8081/ipxe works just fine in console of ipxe

**Comment by wsy0101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
