### ISSUE TITLE
failure creating config struct: unknown keys found during decoding: deviceSelectors

### ISSUE THREAD

**Issue by wsy0101** [siderolabs/sidero#1170]
When updating machine configuration sidero-metal configdata unable to recognize deviceSelectors field.
The machien configuration as follows:
{
    "metadata": {
        "labels": {
            "common-label": "true",
            "zone": "edge-services-master",
            "environment": "edge-services-master"
        }
    },
    "spec": {
        "accepted": true,
        "configPatches": [
            {
                "op": "add",
                "path": "/machine/network",
                "value": {
                    "interfaces": [
                        {
                            "interface": "eth4",
                            "addresses": [
                                "192.168.1.20/24",
                                "2401:8131:b02:ffb1::5688/64"
                            ],
                            "routes": [
                                {
                                    "network": "0.0.0.0/0",
                                    "gateway": "192.168.1.1"
                                },
                                {
                                    "network": "::/0",
                                    "gateway": "2401:8131:b02:ffb1::1/64"
                                }
                            ],
                            "bond": {
                                "interfaces": [],
                                "deviceSelectors": [
                                    {
                                        "busPath": "0000:07:00.0"
                                    }
                                ],
                                "mode": "active-backup"
                            }
                        }
                    ],
                    "nameservers": [
                        "8.8.8.8",
                        "240c::6666"
                    ]
                }
            }
        ]
    }
}

Through curl http://$PUBLIC_IP:8081/configdata? uuid=$SERVER_UUID knows,
failure creating config struct: unknown keys found during decoding:
machine:
    network:
        interfaces:
            - bond:
                deviceSelectors:
                    - busPath: "0000:07:00.0"

**Comment by smira** [comment]
The version of Sidero Metal currently published lags behind, you can try upgrading to the latest alpha release which shouldn't have this issue https://github.com/siderolabs/sidero/releases/tag/v0.6.0-alpha.0

**Comment by wsy0101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
