### ISSUE TITLE
Support for Talos v1.5.0?

### ISSUE THREAD

**Issue by dhess** [siderolabs/sidero#1172]
Hi, thanks for this project, it’s pretty useful!

I see that the other relevant CAPI providers for Talos have just been updated for the Talos v1.5.0 release. How about Sidero, does v0.6.0-alpha.0 support Talos v1.5.0, or is work needed?

**Comment by dhess** [comment]
Answering myself here: I was able to get a Talos v1.5.0 cluster up and running with Sidero `v0.6.0-alpha.0` without any issues. The VIP isn't responding, but that's probably unrelated to Sidero or CAPI in general. Otherwise, everything else so far is working great.

**Comment by smira** [comment]
yes, v0.6.0-alpha.0 will have no issues with Talos v1.5.0 machine config. we will be working this week to get things updated.

**Comment by dhess** [comment]
The only thing I've seen that caused a problem was when, after my bootstrap pivot, the new Sidero service directs the nodes to netboot using the `default` environment, and since that is using `v1.4.0`, that fails due to some of the new machine config settings that are in the node's Talos config. I tore that cluster down, patched `default` to use `v1.5.0`, and then the next attempt at pivoting worked fine.

**Comment by dhess** [comment]
I think we can close this now that v0.6.0 is released, thanks!
