### ISSUE TITLE
How to disable dhcp auto for sidero metal version 0.6.0?

### ISSUE THREAD

**Issue by wsy0101** [siderolabs/sidero#1201]
How to disable dhcp auto for sidero metal version 0.6.0 and where to change its configuration file?

**Comment by smira** [comment]
The question is not clear

**Comment by wsy0101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wsy0101** [comment]
Automatic DHCP Proxy
Sidero v0.6 comes with DHCP proxy which augments the DHCP service provided by the network environment with PXE boot instructions automatically. There is no configuration required besides configuring the network environment DHCP server to assign IPs to the machines.

If the Sidero Metal DHCP proxy server is not enabled, follow the next section to set up the DHCP server.




How to disable it

**Comment by smira** [comment]
There is no way to disable it at the moment, but if not exposed properly on the host, it just won't work
