### ISSUE TITLE
clusterctl move incomplete state after pivot

### ISSUE THREAD

**Issue by johanjk** [siderolabs/sidero#1210]
After pivoting with `clusterctl move`, cluster never reaches `ready` state:

```bash
kubectl wait --for=condition=ready cluster my-cluster
```

Due to:

```yaml
status:
  conditions:
  - lastTransitionTime: [...]
    message: no address were found for node "my-cluster-cp-<uid>"
    reason: WaitingForTalosBoot
    severity: Info
    status: "False"
    type: Ready
```

## diagnostics

Pre-move the `serverbinding` had a `spec.addresses[0]`. But post move it does not.

Resulting in the `metalmachine` not having a `status.addresses` (which is [optional](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine.html#optional-status-fields-1) so fine by the capi standard)

The following [code](https://github.com/siderolabs/sidero/blob/7880ee21b7fa2690a663f260598de9dd247d0060/app/caps-controller-manager/controllers/metalmachine_controller.go#L212-L227) could not find an address on the `serverbinding` object, and hence could not propagate it to the `metalmachine`.

Resulting in triggering of [this error](https://github.com/siderolabs/cluster-api-control-plane-provider-talos/blob/57f188e12f5ba1a4439cb3b16bfa429c58b4519f/controllers/configs.go#L79-L89).

relevant [comment](https://github.com/siderolabs/cluster-api-control-plane-provider-talos/pull/75#issuecomment-948866206)

## dirty workaround

`kubectl edit serverbinding <uuid>` and add `spec.addresses[0]` manually, and the cluster will recover.

But siderolink will end up in a broken state still attempting to push events to the bootstrap cluster:

```json
[talos] siderolink connection configured {
  "component": "controller-runtime",
  "controller": "siderolink.ManagerController",
  "endpoint": "<bootstrap-endpoint>:8081",
  "node_uuid": "<node_uuid>",
  "node_address": "<ipv6_addr>"
}
[talos] controller failed {
  "component": "controller-runtime",
  "controller": "v1alpha1.EventsSinkController",
  "error": "error publishing event: rpc error : code = Unavailable desc = connection error: desc = \x5c"transport: Error while dialing: dial tcp [<ipv6_addr>]:4002: i/o timeout\x5c""
}
```

**Comment by smira** [comment]
Pivoting and self-managing Sidero Metal management cluster is no longer recommended in 0.6

**Comment by johanjk** [comment]
So is this a `wontfix` type bug, or is it working as intended, and I just misconfigured? 

What is the current recommended way? A single node talos cluster as the management cluster? 

Might I suggest a warning in the [docs](https://www.sidero.dev/v0.6/guides/bootstrapping/#pivoting) on it no longer being recommended?

**Comment by smira** [comment]
ok, missed it in one more place in the docs, it shouldn't be there

the recommended approach is to manage the management cluster without Sidero Metal, it can be provisioned manually, or using some other tools.

**Comment by johanjk** [comment]
For others who cannot take no for an answer, what works is the following:
 * run `clusterctl move` as normal.
   This wil leave the `serverbinding` object in a broken state.
   The machine's `siderolink` will also still point back to the old management-cluster.

 * Add a new machine to your cluster with `kubectl edit taloscontrolplane`, and allow it time to start.
   The new machine will boot up with a healthy `serverbinding` and a `siderolink` pointing to the new management-cluster.
 * Add a replica to the sidero-controller `kubectl edit deployment -n sidero-system sidero-controller-manager` and allow the replica to start on the new machine.
    This will allow the new machine to take over the `siderolink`.
 * reset the original machine using `talosctl --nodes <first_machine_ip> reset`. 
    _(as its `serverbinding` is broken, one cannot rely on `kubectl delete machine` to remove it)_. 
    After it has drained, remove the original machine with `kubectl delete machine <first_machine>`.

This will leave the cluster `ready`, all `serverbindings` healthy and `siderolink` functioning.

**Comment by glitchcrab** [comment]
@johanjk thanks for that information, that's very helpful (I also cannot take no for an answer). Regarding your 'clusterctl move', did you find that it copied the `siderolink` secret in the `default` namespace across? The secret is labelled correctly for me with `clusterctl.cluster.x-k8s.io/move: ""`, however when I try a dry-run move the secret doesn't get picked up. Checking out the [clusterctl move provider contract](https://cluster-api.sigs.k8s.io/clusterctl/provider-contract#move), it seems that although the secret is labelled correctly, it would be excluded from discovery because it is in the wrong namespace. How did you get around this?

**Comment by glitchcrab** [comment]
Just to follow up on this, it seems that sidero-controller-manager works just fine if the secret already exists, so I used Flux to deploy the secret to the clusters before the controller is first installed. It _seems_ to work ok.
