### ISSUE TITLE
Require assistance with debugging regarding PXE and the new DHCP proxy

### ISSUE THREAD

**Issue by lieberlois** [siderolabs/sidero#1212]
Hi everyone,

I'm trying to setup Sidero Metal for PXE Booting my SuperMicro Servers. Unfortunately, the servers dont seem to find the sidero-metal-controller during the boot process - i get a classic "pxe media test failure check cable" error. My Sidero Metal instance is running on a talos k8s cluster within the same network as the machines, i have a standard DHCP server handing out leases in my network. Both the Docker container from Talos and the Deployment from Sidero Metal are running in the host network. Using `tcpdump tcpdump -i en0 -pvn port 67 and port 68` I can also see the DHCP broadcast messages in the network on the machine, and (as a test) in a separate docker container with `--network host`. The command `curl -I http://<ip-of-talos-machine>:8081/tftp/snp.efi` also works fine from a different machine in the same network.

According to the [docs](https://www.sidero.dev/v0.6/getting-started/prereq-dhcp/#automatic-dhcp-proxy) the automatic dhcp proxy should allow me to PXE boot machines without any configuration regarding DHCP on my router  - AFAIK I don't need to configure anything (DHCP options like next-server, etc.) in my router.  Am I understanding anything wrong? The documentation doesn't really give any clues on how to debug this.

Thanks in advance guys! If we figure it out and it maybe is something missing in the docs, I am more than willing to contribute to the project :) 

Cheers,
Luis

**Comment by smira** [comment]
Afaik Docker won't allow you to pass through layer 2 packets, this is a docker limitation. It can probably be worked around with some iptables tricks, but nothing I would suggest immediately.

One option is to use manual DHCP configuration for PXE boot, or run management cluster with direct access to layer 2 network.

**Comment by lieberlois** [comment]
Hi @smira - thanks for the quick response. I'm trying to use Sidero Metal for my master thesis and am currently struggling with the Issue mentioned above.

1) Unfortunately I dont have control over the DHCP config in my network, which is why I wanted to try out the DHCP proxy. What would be an alternative? The docs mostly suggest creating a dockerized cluster using Talosctl - would something like k3s work?

2) Regarding Docker Limitations: I thought that using the Network "Host" basically lets the Container use the Host NIC, so layer 2 traffic should work aswell - but I might be wrong.

I would be very thankful for a small explanation to the 2 points above. If you want me to, I'll contribute to the docs so others dont fall into the same trap as I did 🤭

**Comment by smira** [comment]
> Unfortunately I dont have control over the DHCP config in my network, which is why I wanted to try out the DHCP proxy. What would be an alternative? The docs mostly suggest creating a dockerized cluster using Talosctl - would something like k3s work?

the alternative is e.g. to run a machine directly connected to your LAN, you can even keep Sidero Metal where it is, but run a DHCP proxy on your host (not inside Docker)


> Regarding Docker Limitations: I thought that using the Network "Host" basically lets the Container use the Host NIC, so layer 2 traffic should work aswell - but I might be wrong.

You run it with 'network: host' inside Kubernetes, so it exposed to the _Kubernetes_ host, while Kubernetes host is a Docker container which is connected to the Docker bridge, and that has some additional filtering rules in the `iptables`. Docker enables Layer 2 filtering on the bridges via iptables, so it might drop packets to `0.0.0.0` which DHCP is using.

**Comment by lieberlois** [comment]
I see, thanks for the answers! I'm now running Sidero Metal in a k3s cluster (so the containers actually run in the host network and share the interface). Using tcpdump, I figured out that the PXE requests don't seem appear as DISCOVER requests, so I assume its a network configuration error.

At least, the DHCP proxy now seems to receive DHCP requests (not the ones I'm looking for, but one step at a time - MAC address blurred out by me):
```
2023-10-10T11:04:14Z	INFO	dhcp-proxy	ignoring packet	{"source": "xx:xx:xx:xx:xx:xx", "reason": "not a PXE boot request (missing option 93)"}
```

**Comment by smira** [comment]
> "ProxyDHCP service did not reply to request on port 4011

not sure, but googling for it gives a bunch of hits in general

`bad udp cksum` usually appears in tcpdump, I believe it's checksum offloading, can be ignored

as long as Sidero receives and sends the DHCP packet, there shouldn't be much for it

make sure Sidero DHCP responds points back to TFTP/HTTP service in Sidero metal, so you should be able to TFTP the file back from that IP yourself.

**Comment by lieberlois** [comment]
The tcpdump shows, that the PXE client tries to reach the PXE server at port 4011. I think this here might be the issue- do you agree?

https://learn.microsoft.com/en-us/answers/questions/647647/pxe-e55-proxydhcp-service-did-not-reply-to-request

I think its very relevant for the whole Automatic DHCP Proxy issue. Once I have this fixed, I'll be happy to add a PR to the docs for the DHCP automatic proxy :)

**Comment by smira** [comment]
What is the host environment in your case? something Microsoft-ish?

**Comment by lieberlois** [comment]
@smira No, its only BareMetal (Super Microservers) in a network. The router & DHCP is Cisco hardware.

**Comment by smira** [comment]
@lieberlois can you please try to change the `sidero-controller-manager`: `ghcr.io/smira/sidero-controller-manager:v0.6.1`

**Comment by smira** [comment]
idk what is wrong then, it's your main DHCP server? Sidero shouldn't send option 60 anymore

**Comment by lieberlois** [comment]
I can check tomorrow, I'll give you feedback then 👍 thank you so much for the help already! Could you leave the container image up until tomorrow (i.e. dont delete it) ?

**Comment by smira** [comment]
yes, container image will be around forever. it's just 0.6.0 + the fix for option 60, I will post a PR as well

**Comment by lieberlois** [comment]
Nice! I'd be happy to review the PR :)

**Comment by lieberlois** [comment]
I did not get it working with the new docker image yet, still debugging the port 4011 issue 😞  PXE related DHCP options (60, 66 and 67) in the existing DHCP Server are not set, so these shouldn't cause the behavior

**Comment by smira** [comment]
I'm confused on what it might be. interesting enough, existing implementation works with iPXE (if burned to the ROM or loaded)

**Comment by lieberlois** [comment]
@smira Same here 😓 here is a Github Gist of the TCPDUMP

https://gist.github.com/lieberlois/b504a1c6ef47f9a4d31d5f4cfe09295b

The strange thing: the dhcp-proxy obviously even sends a bootp packet with the (correct TFTP Server IP & Filename), the PXE client doesnt seem to get it though. Error on the client says:

CLIENT IP: 0.0.0.0 MASK 0.0.0.0 DHCP IP: 172.27.5.154
PXE-E55: ProxyDHCP service did not reply to request on port 4011.

172.27.5.154 is the IP of my sidero metal instance

**Comment by smira** [comment]
hmmm... you should have CLIENT IP set from your "main" DHCP server as well. you should see both responses  (from Sidero DHCP and your main DHCP) if you're on the same LAN.

I wonder if that's the problem?

**Comment by lieberlois** [comment]
In the tcpdump i can see dhcp acks etc. from the main DHCP server aswell 👍  just not included in the github gist

There is a  difference between your v0.6.1 and the official v0.6.0 though. When using v0.6.0 the PXE client errors with: ```Client IP: 172.27.5.115 Mask: 255.255.255.0 DHCP IP : 172.27.0.100``` (the IP of my networks DHCP server) and when using v0.6.1 it errors with ```Client IP: 0.0.0.0 Mask: 0.0.0.0 DHCP IP : 172.27.5.154``` (the IP of the Sidero Instance)

**Comment by lieberlois** [comment]
Im not sure where that relay agent ip address comes from (in the answer from sidero metal dhcp proxy), do you?

![image](https://github.com/siderolabs/sidero/assets/25712873/695070fa-4d35-463b-8456-20b9fa6ad1dd)

**Comment by smira** [comment]
feels like option 60 is actually needed... (?) as it should use the IP from your main DHCP and augment it with additional PXE boot info. I think we need a real PXE expert here

**Comment by smira** [comment]
it might be interesting if you could run some other DHCP proxy instead of Sidero Metal and make it work with your PXE ROM, and then we could compare the responses

**Comment by lieberlois** [comment]
Very weird - we just pointed the network DHCP Server with option 66 and 67 directly towards Sidero and still get the issue.

I got more info about our networking setup though: the network dhcp server is a dhcp relay server - so maybe thats part of the issue, not sure why it would be though. No ports / addresses are blocked by a firewall etc. aswell

**Comment by lieberlois** [comment]
I almost had a heart attack just now 😆  switched to v0.5.8 with no hope at all left, and it booted! 

Didnt register though, need to figure out which versions to set in my ```~/.cluster-api/clusterctl.yaml``` file to pin sidero version 0.5.8 - any advice here?

**Comment by smira** [comment]
so DHCP proxy breaks things for you? as you actually have DHCP server configured?

**Comment by smira** [comment]
I wonder if you could use 0.6.0 and firewall off ports 67/68 on the Sidero Metal machine... we can add a flag to disable DHCP proxy later

**Comment by lieberlois** [comment]
Yes DHCP Proxy seems to break it

**Comment by lieberlois** [comment]
What do you mean by Firewall off 67/68? There is nothing configured.

Any Idea on the configdata Issue? Is that a Version incompatibility between Sidero 0.5.8 and "latest" for the other components?

**Comment by smira** [comment]
> What do you mean by Firewall off 67/68? There is nothing configured.

I mean the following: Sidero 0.5.8 is old and has some issues with newer versions of Talos

Sidero 0.6.0 is better in any way, but DHCP proxy in it breaks your deployment.

So what if you run Sidero 0.6.0, but on the machine where Sidero is running, you block ports udp 67/68, so that Sidero DHCP proxy doesn't work anymore. And in the follow-up release we will offer an option to disable DHCP proxy.

**Comment by lieberlois** [comment]
FYI: Making progress, I could accept the server and an OS was installed, however now it boots into this and doesnt continue 😄 Ill be so happy when this is finally working!

<img width="732" alt="image" src="https://github.com/siderolabs/sidero/assets/25712873/36de7959-bb0d-4a14-9db5-b60f5a656594">

**Comment by lieberlois** [comment]
Alright, i tried all options, none seem to fix it. 

1. ipxe-sanboot results in the error: 
<img width="737" alt="Pasted Graphic 2" src="https://github.com/siderolabs/sidero/assets/25712873/0c0953ea-163f-48c1-9ed8-2c63c38b3209">

2. ipxe-exit results in (just stops):
<img width="727" alt="Pasted Graphic 3" src="https://github.com/siderolabs/sidero/assets/25712873/a36d513b-5254-4b6d-9665-c1e568a57e5b">

3. http-404 results in (loop):
<img width="726" alt="image" src="https://github.com/siderolabs/sidero/assets/25712873/31250a16-57e6-4701-9b0b-67cb1972df94">



I saw during the install that there was this error, maybe thats an issue aswell. Booting from SSD doesnt appear to work - I either get into the PXE section or it says no boot device found.

<img width="632" alt="initialize sequence failed" src="https://github.com/siderolabs/sidero/assets/25712873/eee84d88-588a-4725-937e-d3cebd0b5a81">

You're right that the all 0s UUID seems weird, the BIOS is pretty old, I'll try to flash a new one tomorrow. I feel like I'm so close to finally get it working, but its a struggle.

**Comment by lieberlois** [comment]
Almost the same issue with v0.6.0:
![image](https://github.com/siderolabs/sidero/assets/25712873/5706896d-3296-4174-ac7d-05f7d8763bdc)

The server has properly discovered the disk though:
```yaml
      storage:
        deviceCount: 1
        devices:
        - deviceName: /dev/sda
          productName: SAMSUNG SSD PM80
          size: 64023257088
          type: SSD
          wwid: naa.50000f0056424431
        totalSize: 59 GB
???

**Comment by smira** [comment]
There seems to be more issues here: 

1. you should be setting install disk as a config patch, even though `/dev/sda` should be a default iirc: https://www.sidero.dev/v0.6/resource-configuration/servers/#installation-disk
2. Sidero Metal should detect failed install like that... so probably there's something with SideroLink connection back from the machine to Sidero Metal.

**Comment by lieberlois** [comment]
<img width="738" alt="image" src="https://github.com/siderolabs/sidero/assets/25712873/c5b40359-3c68-4fef-bae1-236d41555971">


You were absolutely right! That was it! I'm noting everything down and will create a PR for the docs 😄 thank you soooo much @smira , you really gave me hope again for my masters thesis 🥳
