### ISSUE TITLE
DHCP proxy failed to emit packets from local bootstrap cluster created by `talosctl`

### ISSUE THREAD

**Issue by braska** [siderolabs/sidero#1286]
I was following instruction here to prepare temporary bootstrap cluster: https://www.sidero.dev/v0.6/getting-started/prereq-kubernetes/

But I stumble upon situation when PXE-booting machine can obtain IP from my DHCP server, but not receiving any response back from Sidero DHCP proxy. I tried to trace what is happenning with netowork on host where I run this temp bootstrap cluster and here as what I found out using Wireshark:
![image](https://github.com/siderolabs/sidero/assets/3268276/7881073d-5b57-45c4-b936-c3c1059415a4)

As you can see packets from PXE-booting machine arrived and was passed into Sidero Controller. The Sidero controller tried to reply but "Boot Reply" packet can't leave my machine. I am not a networking expect, but I found this comment: https://github.com/siderolabs/sidero/issues/1212#issuecomment-1753828577 saying:
> Afaik Docker won't allow you to pass through layer 2 packets, this is a docker limitation.

And it totally makes sense. But I don't understand why local docker-based cluster recommended here: https://www.sidero.dev/v0.6/getting-started/prereq-kubernetes/ Is it supposed to work at all? Is it mistake in documentation?

**Comment by braska** [comment]
I will try to capture and re-broadcast DHCP packets from Docker bridge network as recommended [here](https://serverfault.com/a/1036270) and post my findings.

**Comment by smira** [comment]
DHCP proxy can be disabled in this case. Docker installs firewall rules which match raw packets, and they drop some DHCP packets.
