### ISSUE TITLE
Use "host" instead of "server"

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/sidero#75]
In the next version of Sidero (v0.2), we should rename "Server" to "Host" (still don't love it, and open to alternatives).

**Comment by smira** [comment]
Node?

**Comment by andrewrynhard** [comment]
> Node?

We can't do node because then `kubectl get nodes` would have 2 different meanings.

**Comment by smira** [comment]
`MetalServer` as more specific than `Server` as one more idea

**Comment by Ulexus** [comment]
IMO:  a Machine is what is currently a Server.  That is, it is a piece of hardware which is not in and of itself a part of anything.  It is simply a Machine.

A Server, on the other hand, is a Machine which has been assigned the role of Server.  That is, it has something in particular which it will serve.

A Node is a computing member of a Cluster, as it already is in Kubernetes.

**Comment by Ulexus** [comment]
Obviously, switching those up at this point is probably a "Bad Idea"

**Comment by andrewrynhard** [comment]
> IMO: a Machine is what is currently a Server. That is, it is a piece of hardware which is not in and of itself a part of anything. It is simply a Machine.
> 
> A Server, on the other hand, is a Machine which has been assigned the role of Server. That is, it has something in particular which it will serve.
> 
> A Node is a computing member of a Cluster, as it already is in Kubernetes.

Agree. But, unfortunately we can't use `Machine` because that is a cluster api type.

**Comment by makuser** [comment]
This can be closed now, right?

**Comment by smira** [comment]
yes, no plans to change the names
