### ISSUE TITLE
Raspberry Pi 4 as Server: Building boot folder contents

### ISSUE THREAD

**Issue by mhwilkes** [siderolabs/sidero#882]
Hello,

I have been trying to follow the guide to make RPi's usable as servers with sidero to help automate building clusters with talos.

Following the guide and running the make as specified in the guide results in the following:

`error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to solve LLB: requested experimental feature mergeop  is not supported by build server, please update docker`

This is on Windows 11 using gnu make from chocolatey.
Utilizing Docker Desktop for the docker build portion (4.9.0 80466)

Have been struggling to figure out if this is something that I am doing wrong or if others have ran into this issue too

Thanks

**Comment by frezbo** [comment]
you probably need to create a `buildx` driver via `docker buildx create --use`
